<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jo_template"
 *
 * Auto generated by Extension Builder 2016-02-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/
$EM_CONF[$_EXTKEY] = [
    'title' => 'JO Template Base',
    'description' => 'JO Template Base',
    'category' => 'plugin',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '11.5.23',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-11.5'
        ],
        'conflicts' => [],
        'suggests' => []
    ],
    'autoload' => [
        'psr-4' => [
            'JO\\JoTemplate\\' => 'Classes'
        ]
    ]
];
